[metadata]
name = ai-restaurant-monitoring
version = 1.0.0
author = Sauciuc George
author_email = georgesauciuc16@gmail.com
description = Sistem inteligent de monitorizare a activității meselor dintr-un restaurant folosind detecție video și analiză statistică
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/utilizator/ai-restaurant-monitoring
license = MIT
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
packages = find:
python_requires = >=3.12
include_package_data = True
install_requires =
    numpy
    pandas
    opencv-python
    matplotlib
    openpyxl
    tk
    customtkinter
    tkcalendar
    psutil
    torch>=2.0
    Pillow
    ultralytics

[options.package_data]
* = *.mp3, *.wav, *.css, *.js, *.html

[options.extras_require]
dev =
    black
    flake8
    isort
